language: python
python:
  - "2.7"
env:
  - DB=mysql C2G_SELENIUM_WEBDRIVER=firefox C2G_HEADLESS_TESTS=1 
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq unzip flashplugin-installer 
install:
  - pip install pyvirtualdisplay
  - pip install -r requirements.txt --use-mirrors
before_script:
  - bash main/travis/setup.sh
  - mysql -e 'create database class2go'
  - cd main
script: 
  - python manage.py test -v 2
notifications:
  irc: 
    channels:
      - "irc.freenode.org#class2go-internal"
    template:
      - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}"
      - "Build details : %{build_url}"
    use_notice: true
    skip_join: true
